/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export declare function rnnForwardNativeInto(xData: Float32Array, wxhData: Float32Array, whhData: Float32Array, bhData: Float32Array, seqLen: number, batchSize: number, units: number, hiddenUnits: number, isRelu: boolean, hSeqData: Float32Array, dactData: Float32Array): void
export declare function rnnBackwardNativeInto(xData: Float32Array, wxhData: Float32Array, whhData: Float32Array, hSeqData: Float32Array, dactData: Float32Array, extErrData: Float32Array, seqLen: number, batchSize: number, units: number, hiddenUnits: number, dwxhData: Float32Array, dwhhData: Float32Array, dbhData: Float32Array, dxData: Float32Array): void
export declare function lstmForwardNativeInto(xData: Float32Array, wxiData: Float32Array, whiData: Float32Array, biData: Float32Array, wxfData: Float32Array, whfData: Float32Array, bfData: Float32Array, wxoData: Float32Array, whoData: Float32Array, boData: Float32Array, wxgData: Float32Array, whgData: Float32Array, bgData: Float32Array, seqLen: number, batchSize: number, units: number, hiddenUnits: number, hSeqData: Float32Array, cSeqData: Float32Array, iSeqData: Float32Array, fSeqData: Float32Array, oSeqData: Float32Array, gSeqData: Float32Array): void
export declare function lstmBackwardNativeInto(xData: Float32Array, wxiData: Float32Array, whiData: Float32Array, wxfData: Float32Array, whfData: Float32Array, wxoData: Float32Array, whoData: Float32Array, wxgData: Float32Array, whgData: Float32Array, hSeqData: Float32Array, cSeqData: Float32Array, iSeqData: Float32Array, fSeqData: Float32Array, oSeqData: Float32Array, gSeqData: Float32Array, extErrData: Float32Array, seqLen: number, batchSize: number, units: number, hiddenUnits: number, dwxiData: Float32Array, dwhiData: Float32Array, dbiData: Float32Array, dwxfData: Float32Array, dwhfData: Float32Array, dbfData: Float32Array, dwxoData: Float32Array, dwhoData: Float32Array, dboData: Float32Array, dwxgData: Float32Array, dwhgData: Float32Array, dbgData: Float32Array, dxData: Float32Array): void
export declare function gruForwardNativeInto(xData: Float32Array, wxrData: Float32Array, whrData: Float32Array, brData: Float32Array, wxzData: Float32Array, whzData: Float32Array, bzData: Float32Array, wxhData: Float32Array, whhData: Float32Array, bhData: Float32Array, seqLen: number, batchSize: number, units: number, hiddenUnits: number, reverse: boolean, hSeqData: Float32Array, rSeqData: Float32Array, zSeqData: Float32Array, nSeqData: Float32Array): void
export declare function gruBackwardNativeInto(xSeqData: Float32Array, wxrData: Float32Array, whrData: Float32Array, wxzData: Float32Array, whzData: Float32Array, wxhData: Float32Array, whhData: Float32Array, hSeqData: Float32Array, rSeqData: Float32Array, zSeqData: Float32Array, nSeqData: Float32Array, extErrData: Float32Array, seqLen: number, batchSize: number, units: number, hiddenUnits: number, reverse: boolean, dwxrData: Float32Array, dwhrData: Float32Array, dbrData: Float32Array, dwxzData: Float32Array, dwhzData: Float32Array, dbzData: Float32Array, dwxhData: Float32Array, dwhhData: Float32Array, dbhData: Float32Array, dxData: Float32Array): void
export interface MaskedSparseSoftmaxCrossEntropyResult {
  loss: number
  validTokens: number
}
export interface EmbeddingSparseBackwardResult {
  uniqueIndices: Int32Array
  grad: Float32Array
}
export declare function dotProduct(aData: Float32Array, aShape: Array<number>, bData: Float32Array, bShape: Array<number>, transA: boolean, transB: boolean): Float32Array
export declare function dotProductInto(aData: Float32Array, aShape: Array<number>, bData: Float32Array, bShape: Array<number>, outData: Float32Array, transA: boolean, transB: boolean): void
export declare function dotProductIntoDims(aData: Float32Array, aRows: number, aCols: number, bData: Float32Array, bRows: number, bCols: number, outData: Float32Array, transA: boolean, transB: boolean): void
export declare function addMatricesInto(a: Float32Array, b: Float32Array, out: Float32Array): void
export declare function subMatricesInto(a: Float32Array, b: Float32Array, out: Float32Array): void
export declare function mulMatricesInto(a: Float32Array, b: Float32Array, out: Float32Array): void
export declare function divMatricesInto(a: Float32Array, b: Float32Array, out: Float32Array): void
export declare function softmaxNativeInto(data: Float32Array, rows: number, cols: number, isRow: boolean, out: Float32Array): void
export declare function softmaxBackwardNativeInto(sData: Float32Array, gData: Float32Array, rows: number, cols: number, isRow: boolean, out: Float32Array): void
export declare function layerNormNativeInto(xData: Float32Array, gamma: Float32Array, beta: Float32Array, rows: number, cols: number, eps: number, outRes: Float32Array, outNorm: Float32Array, outMeans: Float32Array, outStds: Float32Array): void
export declare function layerNormBackwardNativeInto(errData: Float32Array, normData: Float32Array, gammaData: Float32Array, rows: number, cols: number, stdData: Float32Array, dGammaOut: Float32Array, dBetaOut: Float32Array, dxOut: Float32Array): void
export declare function reluNativeInto(input: Float32Array, outRes: Float32Array, outGrad: Float32Array): void
export declare function sigmoidNativeInto(input: Float32Array, outRes: Float32Array, outGrad: Float32Array): void
export declare function tanhNativeInto(input: Float32Array, outRes: Float32Array, outGrad: Float32Array): void
export declare function embeddingForwardNativeInto(indices: Array<number>, weightData: Float32Array, vocabSize: number, embeddingDim: number, padTokenId: number | undefined | null, out: Float32Array): void
export declare function embeddingForwardNativeInt32Into(indices: Int32Array, weightData: Float32Array, vocabSize: number, embeddingDim: number, padTokenId: number | undefined | null, out: Float32Array): void
export declare function embeddingBackwardNative(indices: Array<number>, errData: Float32Array, gradData: Float32Array, vocabSize: number, embeddingDim: number, padTokenId?: number | undefined | null): void
export declare function embeddingBackwardNativeInt32(indices: Int32Array, errData: Float32Array, gradData: Float32Array, vocabSize: number, embeddingDim: number, padTokenId?: number | undefined | null): void
export declare function embeddingBackwardSparseNative(indices: Int32Array, errData: Float32Array, embeddingDim: number, padTokenId?: number | undefined | null): EmbeddingSparseBackwardResult
export declare function convolutionNativeInto(aData: Float32Array, aRows: number, aCols: number, kData: Float32Array, kRows: number, kCols: number, out: Float32Array): void
export declare function convBackwardInputNativeInto(errData: Float32Array, errRows: number, errCols: number, inputData: Float32Array, inputRows: number, inputCols: number, outRows: number, outCols: number, out: Float32Array): void
export declare function applyAttentionMaskNative(data: Float32Array, padMask: Array<boolean>, rows: number, cols: number, scale: number): void
export declare function adamUpdateNative(grad: Float32Array, m: Float32Array, v: Float32Array, buffer: Float32Array, t: number, alpha: number, beta1: number, beta2: number, epsilon: number): void
export declare function adamSparseUpdateNative(indices: Int32Array, grad: Float32Array, weight: Float32Array, m: Float32Array, v: Float32Array, t: number, alpha: number, beta1: number, beta2: number, epsilon: number, vocabSize: number, embeddingDim: number): void
export declare function sgdUpdateNative(grad: Float32Array, out: Float32Array, alpha: number): void
export declare function sgdSparseUpdateNative(indices: Int32Array, grad: Float32Array, weight: Float32Array, alpha: number, vocabSize: number, embeddingDim: number): void
export declare function adagradUpdateNative(grad: Float32Array, sum: Float32Array, out: Float32Array, alpha: number, epsilon: number): void
export declare function adagradSparseUpdateNative(indices: Int32Array, grad: Float32Array, weight: Float32Array, sum: Float32Array, alpha: number, epsilon: number, vocabSize: number, embeddingDim: number): void
export declare function momentumUpdateNative(grad: Float32Array, v: Float32Array, out: Float32Array, alpha: number, beta: number): void
export declare function momentumSparseUpdateNative(indices: Int32Array, grad: Float32Array, weight: Float32Array, v: Float32Array, alpha: number, beta: number, vocabSize: number, embeddingDim: number): void
export declare function nagUpdateNative(grad: Float32Array, v: Float32Array, out: Float32Array, alpha: number, beta: number): void
export declare function nagSparseUpdateNative(indices: Int32Array, grad: Float32Array, weight: Float32Array, v: Float32Array, alpha: number, beta: number, vocabSize: number, embeddingDim: number): void
export declare function addInPlace(a: Float32Array, b: Float32Array): void
export declare function subInPlace(a: Float32Array, b: Float32Array): void
export declare function mulInPlace(a: Float32Array, b: Float32Array): void
export declare function mseNative(yTrue: Float32Array, yPred: Float32Array): Array<number>
export declare function addBiasNative(data: Float32Array, bias: Float32Array, rows: number, cols: number): void
export declare function sumAxisNative(data: Float32Array, rows: number, cols: number, axis: number, out: Float32Array): void
export declare function clipGradientsNative(data: Float32Array, limit: number): void
export declare function denseLinearBackwardNativeInto(errActivation: Float32Array, input: Float32Array, weight: Float32Array, outputUnits: number, units: number, seqLen: number, clipLimit: number, gradWeightOut: Float32Array, gradBiasOut: Float32Array, prevErrOut: Float32Array): void
export declare function maskedSparseSoftmaxCrossEntropyInto(logits: Float32Array, inputTokens: Float32Array, targets: Float32Array, seqLen: number, batchSize: number, vocabSize: number, padTokenId: number | undefined | null, outGrad: Float32Array): MaskedSparseSoftmaxCrossEntropyResult
export declare function projectLastTokenLogitsNativeInto(hidden: Float32Array, weight: Float32Array, bias: Float32Array, units: number, seqLen: number, batchSize: number, vocabSize: number, out: Float32Array): void
export declare function multiHeadAttentionForwardNativeInto(qData: Float32Array, kData: Float32Array, vData: Float32Array, padMask: Array<boolean>, heads: number, headUnits: number, seqLen: number, batchSize: number, scale: number, outData: Float32Array, attentionData: Float32Array): void
export declare function multiHeadAttentionBackwardNativeInto(qData: Float32Array, kData: Float32Array, vData: Float32Array, attentionData: Float32Array, dOutData: Float32Array, padMask: Array<boolean>, heads: number, headUnits: number, seqLen: number, batchSize: number, scale: number, dQOut: Float32Array, dKOut: Float32Array, dVOut: Float32Array): void
export type NativeBPE = NativeBpe
export declare class NativeBpe {
  constructor(vocab: Record<string, number>, merges: Array<Array<string>>, unkTokenId: number, wordBoundary: string)
  encode(tokens: Array<string>): Array<number>
}
