/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export declare function dotProduct(aData: Float64Array, aShape: Array<number>, bData: Float64Array, bShape: Array<number>, transA: boolean, transB: boolean): Float64Array
export declare function addMatrices(a: Float64Array, b: Float64Array): Float64Array
export declare function subMatrices(a: Float64Array, b: Float64Array): Float64Array
export declare function mulMatrices(a: Float64Array, b: Float64Array): Float64Array
export declare function divMatrices(a: Float64Array, b: Float64Array): Float64Array
export declare function addInPlace(a: Float64Array, b: Float64Array): void
export declare function subInPlace(a: Float64Array, b: Float64Array): void
export declare function mulInPlace(a: Float64Array, b: Float64Array): void
export declare function softmaxNative(data: Float64Array, rows: number, cols: number, isRow: boolean): Float64Array
export declare function softmaxBackwardNative(sData: Float64Array, gData: Float64Array, rows: number, cols: number, isRow: boolean): Float64Array
export declare function layerNormNative(xData: Float64Array, gamma: Float64Array, beta: Float64Array, rows: number, cols: number, eps: number): Array<Float64Array>
export declare function applyAttentionMaskNative(data: Float64Array, padMask: Array<boolean>, rows: number, cols: number, scale: number): void
export declare function adamUpdateNative(grad: Float64Array, m: Float64Array, v: Float64Array, buffer: Float64Array, t: number, alpha: number, beta1: number, beta2: number, epsilon: number): void
export declare function reluNative(input: Float64Array): Array<Float64Array>
export declare function sigmoidNative(input: Float64Array): Array<Float64Array>
export declare function tanhNative(input: Float64Array): Array<Float64Array>
export declare function mseNative(yTrue: Float64Array, yPred: Float64Array): Array<number>
export declare function embeddingForwardNative(indices: Array<number>, weightData: Float64Array, vocabSize: number, embeddingDim: number, padTokenId?: number | undefined | null): Float64Array
export declare function embeddingBackwardNative(indices: Array<number>, errData: Float64Array, gradData: Float64Array, vocabSize: number, embeddingDim: number, padTokenId?: number | undefined | null): void
export declare function convolutionNative(aData: Float64Array, aRows: number, aCols: number, kData: Float64Array, kRows: number, kCols: number): Float64Array
export declare function convBackwardInputNative(errData: Float64Array, errRows: number, errCols: number, inputData: Float64Array, inputRows: number, inputCols: number, outRows: number, outCols: number): Float64Array
