/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export declare class NativeSpikingNetwork {
  constructor(numNeurons: number, beta: number, defaultThreshold: number)
  connect(pre: number, post: number, weight: number): void
  injectCurrent(neuronIdx: number, current: number): void
  step(): void
  resetState(): void
  getSpikes(): Array<number>
  getPotentials(): Array<number>
  updateStdp(learningRate: number, tauPlus: number, tauMinus: number, aPlus: number, aMinus: number, wMax: number, wMin: number): void
  saveToFile(filepath: string): void
  loadFromFile(filepath: string): void
}
