/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export declare function dotProductAddOnlyNative(aData: Float32Array, aRowsOrig: number, aColsOrig: number, bData: Float32Array, bRowsOrig: number, bColsOrig: number, transA: boolean, transB: boolean, outData: Float32Array): void
export declare function lifStepNative(potentials: Float32Array, dot: Float32Array, spikes: Float32Array, lastPotentials: Float32Array, beta: number, threshold: number): void
export declare function maskSurrogateNative(errorSignal: Float32Array, potentials: Float32Array, threshold: number, windowSize: number): void
export declare function applyAddOnlyDeltaNative(kernel: Float32Array, bias: Float32Array, inputs: Float32Array, errorSignal: Float32Array, learningRate: number, batch: number, inFeatures: number, units: number, useBias: boolean): void
export declare class NativeSpikingNetwork {
  constructor(numNeurons: number, beta: number, defaultThreshold: number)
  connect(pre: number, post: number, weight: number): void
  injectCurrent(neuronIdx: number, current: number): void
  inhibitRange(startIdx: number, endIdx: number, exceptIdx: number, current: number): void
  step(): void
  resetState(): void
  getSpikes(): Array<number>
  getPotentials(): Array<number>
  updateStdp(learningRate: number, tauPlus: number, tauMinus: number, aPlus: number, aMinus: number, wMax: number, wMin: number): void
  saveToFile(filepath: string): void
  loadFromFile(filepath: string): void
}
